In [7]:
import wikipedia as wiki
import pandas as pd

In [8]:
search_string = 'Social Network Analysis'
page = wiki.page (search_string)
content = page.content
content[0:680]

'Social network analysis (SNA) is the process of investigating social structures  through the use of networks and graph theory. It characterizes networked structures in terms of nodes (individual actors, people, or things within the network) and the ties, edges, or links (relationships or interactions) that connect them.  Examples of social structures commonly visualized through social network analysis include social media networks, meme proliferation, information circulation, friendship and acquaintance networks, business networks, knowledge networks, difficult working relationships, collaboration graphs, kinship, disease transmission, and sexual relationships. These netw'

In [9]:
links = page.links
links[0:10]

['Account verification',
 'Actor-network theory',
 'Adjacency list',
 'Adjacency matrix',
 'Adolescent clique',
 'Affinity fraud',
 'Agent-based model',
 'Albert-László Barabási',
 'Alexis de Tocqueville',
 'Algorithm']

In [14]:
url = 'https://en.wikipedia.org/wiki/Social_network_analysis'
data = pd.read_html(url)
df1 = data[1]
df1.tail()

                                                    0
18                                           Dynamics
19           Boolean network agent based Epidemic/SIR
20                                    ListsCategories
21  Topics Software Network scientists Category:Ne...
22                                                vte

In [22]:
url1 = 'https://en.wikipedia.org/wiki/Crime_in_Oregon#Criminals'
data1 = pd.read_html(url1)
df2 = data[1]
df2.tail()

,Name,Lifespan,Crime(s),Notes,Ref.
15,Harry Charles Moore,1941–1997,Murder,Second person executed in the state of Oregon ...,[21]
16,Dayton Leroy Rogers,1953–,Serial murder,Murdered at least 6 women near Molalla between...,[22]
17,Ward Weaver III,1963–,Murder,Committed 2002 murders of Ashley Pond and Mira...,[23]
18,Randall Woodfield,1950–,"Serial murder, rape, robbery",Committed multiple crimes along Interstate 5 i...,[24]
19,Douglas Franklin Wright,1940–1996,Serial murder,First criminal executed by lethal injection in...,[25]