# Introduction
This notebook is to learn and show the output from the step of understanding Network Science using Python by David Knickerbocker.

In [ ]:
import wikipedia as wiki
import pandas as pd

In [8]:
search_string = 'Social Network Analysis'
page = wiki.page (search_string)
content = page.content
content[0:680]

'Social network analysis (SNA) is the process of investigating social structures  through the use of networks and graph theory. It characterizes networked structures in terms of nodes (individual actors, people, or things within the network) and the ties, edges, or links (relationships or interactions) that connect them.  Examples of social structures commonly visualized through social network analysis include social media networks, meme proliferation, information circulation, friendship and acquaintance networks, business networks, knowledge networks, difficult working relationships, collaboration graphs, kinship, disease transmission, and sexual relationships. These netw'

In [9]:
links = page.links
links[0:10]

['Account verification',
 'Actor-network theory',
 'Adjacency list',
 'Adjacency matrix',
 'Adolescent clique',
 'Affinity fraud',
 'Agent-based model',
 'Albert-László Barabási',
 'Alexis de Tocqueville',
 'Algorithm']

In [14]:
url = 'https://en.wikipedia.org/wiki/Social_network_analysis'
data = pd.read_html(url)
df1 = data[1]
df1.tail()

                                                    0
18                                           Dynamics
19           Boolean network agent based Epidemic/SIR
20                                    ListsCategories
21  Topics Software Network scientists Category:Ne...
22                                                vte

In [22]:
url1 = 'https://en.wikipedia.org/wiki/Crime_in_Oregon#Criminals'
data1 = pd.read_html(url1)
df2 = data[1]
df2.tail()

,Name,Lifespan,Crime(s),Notes,Ref.
15,Harry Charles Moore,1941–1997,Murder,Second person executed in the state of Oregon ...,[21]
16,Dayton Leroy Rogers,1953–,Serial murder,Murdered at least 6 women near Molalla between...,[22]
17,Ward Weaver III,1963–,Murder,Committed 2002 murders of Ashley Pond and Mira...,[23]
18,Randall Woodfield,1950–,"Serial murder, rape, robbery",Committed multiple crimes along Interstate 5 i...,[24]
19,Douglas Franklin Wright,1940–1996,Serial murder,First criminal executed by lethal injection in...,[25]

In [ ]:
import nltk 
nltk.download()
from nltk.corpus import gutenberg
gutenberg.fileids()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

['austen-emma.txt',
 'austen-persuasion.txt',
 'bryant-stories.txt',
 'shakespeare-hamlet.txt']

In [5]:
file = 'blake-poems.txt'

data = gutenberg.raw(file)
data[0:600]

'[Poems by William Blake 1789]\n\n \nSONGS OF INNOCENCE AND OF EXPERIENCE\nand THE BOOK of THEL\n\n\n SONGS OF INNOCENCE\n \n \n INTRODUCTION\n \n Piping down the valleys wild,\n   Piping songs of pleasant glee,\n On a cloud I saw a child,\n   And he laughing said to me:\n \n "Pipe a song about a Lamb!"\n   So I piped with merry cheer.\n "Piper, pipe that song again;"\n   So I piped: he wept to hear.\n \n "Drop thy pipe, thy happy pipe;\n   Sing thy songs of happy cheer:!"\n So I sang the same again,\n   While he wept with joy to hear.\n \n "Piper, sit thee down and write\n   In a book, that all may read."\n So he vanish\'d'

In [ ]:
import requests

url = 'https://www.gutenberg.org/ebooks/5200.txt'
data = requests.get(url).text
data

'<!DOCTYPE html>\n<html class="client-nojs" lang="en" dir="ltr">\n<head>\n <meta charset="UTF-8"/>\n\n<title>404 | Project Gutenberg</title>\n <link rel="stylesheet" href="/gutenberg/style.css?v=1.1">\n <link rel="stylesheet" href="/gutenberg/collapsible.css?1.1">\n <link rel="stylesheet" href="/gutenberg/new_nav.css?v=1.321231">\n<link rel="stylesheet" href="/gutenberg/pg-desktop-one.css">\n <meta name="viewport" content="width=device-width, initial-scale=1">\n <meta name="keywords" content="books, ebooks, free, kindle, android, iphone, ipad"/>\n <meta name="google-site-verification" content="wucOEvSnj5kP3Ts_36OfP64laakK-1mVTg-ptrGC9io"/>\n <meta name="alexaVerifyID" content="4WNaCljsE-A82vP_ih2H_UqXZvM"/>\n <link rel="copyright" href="https://www.gnu.org/copyleft/fdl.html"/>\n <link rel="icon" type="image/png" href="/gutenberg/favicon.ico" sizes="16x16" />\n <meta property="og:title"        content="Project Gutenberg" />\n <meta property="og:type"         content="website" />\n <meta property="og:url"          content="https://www.gutenberg.org/" />\n <meta property="og:description"  content="Project Gutenberg is a library of free eBooks." />\n <meta property="fb:admins"       content="615269807" />\n <meta property="fb:app_id"       content="115319388529183" />\n <meta property="og:site_name"    content="Project Gutenberg" />\n <meta property="og:image"        content="https://www.gutenberg.org/gutenberg/pg-logo-144x144.png" />\n </head>\n<body>\n  <div class="container"><!-- start body --><nav>\n  <!--<div id="main_logo"> -->\n  <a id="main_logo" href="/" class="no-hover">\n    <img src="/gutenberg/pg-logo-129x80.png" alt="Project Gutenberg" draggable="false" />\n  </a>\n  <!--\t</div>-->\n  <div id="menu">\n    <label for="tm" id="toggle-menu">Menu<span class="drop-icon">&#9662;</span></label>\n    <input type="checkbox" id="tm" />\n    <ul class="main-menu cf">\n      <li>\n\t<a href="/about/">About\n          <span class="drop-icon">&#9662;</span>\n      \t</a>\n        <label title="Toggle Drop-down" class="drop-icon" for="sm0">&#9662;</label>\n     \t<input type="checkbox" id="sm0" />\n     \t<ul class="sub-menu">\n\t  <li><a href="/about/">About Project Gutenberg</a></li>\n          <li><a href="/policy/collection_development.html">Collection Development</a></li>\n          <li><a href="/about/contact_information.html">Contact Us</a></li>\n          <li><a href="/about/background/">History &amp; Philosophy</a></li>\n          <li><a href="/policy/permission.html">Permissions &amp; License</a></li>\n          <li><a href="/policy/privacy_policy.html">Privacy Policy</a></li>\n          <li><a href="/policy/terms_of_use.html">Terms of Use</a></li>\n\t</ul>\n      </li>\n      <li>\n\t<a href="/ebooks/">Search and Browse\n      \t  <span class="drop-icon">&#9662;</span>\n      \t</a>\n\t<label title="Toggle Drop-down" class="drop-icon" for="sm8">&#9662;</label>\n        <input type="checkbox" id="sm8" />\n        <ul class="sub-menu">\n\t  <li><a href="/ebooks/">Book Search</a></li>\n\t  <li><a href="/ebooks/bookshelf/">Bookshelves</a></li>\n\t  <li><a href="/browse/scores/top">Frequently Downloaded</a></li>\n\t  <li><a href="/ebooks/offline_catalogs.html">Offline Catalogs</a></li>\n\t</ul>\n      </li>\n      <li>\n\t<a href="/help/">Help\n          <span class="drop-icon">&#9662;</span>\n   \t</a>\n         <label title="Toggle Drop-down" class="drop-icon" for="sm3">&#9662;</label>\n   \t<input type="checkbox" id="sm3" />\n    \t<ul class="sub-menu">\n          <li><a href="/help/">All help topics &rarr;</a></li>\n          <li><a href="/help/copyright.html">Copyright How-To</a></li>\n          <li><a href="/help/errata.html">Errata, Fixes and Bug Reports</a></li>\n          <li><a href="/help/file_formats.html">File Formats</a></li>\n          <li><a href="/help/faq.html">Frequently Asked Questions</a></li>\n          <li><a href="/policy/">Policies &rarr;</a></li>\n          <li><a href="/help/public_domain_ebook_submission.html">Public Domain eBook Submission</a></li>\n          <li><a href="/help/submitting_your_own_work.html">Submitting Your Own Work</a></li>\n          <li><a href="/help/mobile.html">Tablets, Phones and eReaders</a></li>\n          <li><a href="/attic/">The Attic &rarr;</a></li>\n        </ul>\n      </li>\n      <li><a href="/donate/">Donate</a></li>\n    </ul>\n  </div>\n  <div class="donate">\n  <div class="searchbox">\n    <form method="get" action="/ebooks/search/" accept-charset="utf-8" enctype="multipart/form-data" class="searchbox">\n      <input type="text" value="" id="menu-book-search" name="query" class="searchInput" title="Quick search" tabindex="20" size="20" maxlength="80" placeholder="  Quick search" />\n      <input type="submit" name="submit_search" value="Go!" style="vertical-align:middle;" />\n    </form>\n  </div>\n    <form class="donatelink" action="https://www.paypal.com/cgi-bin/webscr" method="post" target="new">\n      <p><a href="/donate/">Ways to donate</a></p>\n      <input type="hidden" name="cmd" value="_s-xclick" />\n      <input type="hidden" name="hosted_button_id" value="XKAL6BZL3YPSN" />\n      <input class="donbtn" type="image" src="/pics/en_US.gif" name="submit" alt="Donate via PayPal" />\n    </form>\n  </div>\n</nav>\n<div class="page_content"><!-- start content -->\n\n        <h1 id="error-404">Error 404</h1>\n\n<p>Sorry, but our website does not have the page you requested.</p>\n\n<p>Maybe you have just a wrong url. Go to <a href="/">www.gutenberg.org</a> to see whether the error persists.</p>\n\n<p>If you think something is broken, follow the â\x80\x9cContact Informationâ\x80\x9d link at the bottom of this page if you would like to report it.</p>\n\n\n   </div><!--content ending-->\n  </div><!-- body ending -->\n   <div class="footer"><!-- start footer -->  <ul>\n      <li>\n        <a href="/policy/privacy_policy.html" title="Privacy Policy">Privacy policy</a>\n      </li>\n      <li>\n        <a href="/about/" title="About Project Gutenberg">About Project Gutenberg</a>\n      </li>\n      <li>\n        <a href="/policy/terms_of_use.html" title="Terms of Use">Terms of Use</a>\n      </li>\n      <li>\n        <a href="/about/contact_information.html" title="Contact Information">Contact Information</a>\n      </li>\n      <li><a href="/help/" title="Get Help">Get Help</a></li>\n\n  </ul>\n\n  <a href="https://www.ibiblio.org/" title="Project Gutenberg is hosted by ibiblio">\n   <img src="/gutenberg/ibiblio-logo.png" alt="iBiblio">\n  </a>\n</div><!-- footer ending-->\n\n </body>\n</html>\n'

:

In [6]:
from bs4 import BeautifulSoup
import requests

url = 'http://english.ryukyushimpo.jp/2022/05/17/34668/'
data = requests.get(url).text
soup = BeautifulSoup(data, 'html.parser')
links = soup.find_all('a', href=True)
links

[<a href="http://english.ryukyushimpo.jp">Home</a>,
 <a href="http://english.ryukyushimpo.jp">Ryukyu Shimpo – Okinawa, Japanese newspaper, local news</a>,
 <a href="http://english.ryukyushimpo.jp/special-feature-okinawa-holds-mass-protest-rally-against-us-base/">Special Feature: Okinawa holds mass protest rally against US base</a>,
 <a href="https://ryukyushimpo.jp/news/entry-1514895.html" onclick="javascript:pageTracker._trackPageview('/outgoing/ryukyushimpo.jp/news/entry-1514895.html');">Go to Japanese </a>,
 <a class="twitter-share-button" data-lang="en" data-text="300 tourism industry personnel rally for COVID cooperation subsidies, 3,000 signatures support" data-url="http://english.ryukyushimpo.jp/2022/05/17/34668/" href="https://twitter.com/share" onclick="javascript:pageTracker._trackPageview('/outgoing/twitter.com/share');">Tweet</a>,
 <a href="http://english.ryukyushimpo.jp/2022/05/12/34661/" rel="prev">In joint survey conducted by the Ryukyu Shimpo and Mainichi Shimbun, 61% of Okinawans think the concentration of bases in Okinawa “unfair,” while only 40% of people nationwide agree</a>,
 <a href="http://english.ryukyushimpo.jp/2022/05/17/34671/" rel="next">Okinawa Coca Cola Bottling to issue special retro-design can to celebrate the 50th anniversary of the reversion</a>,
 <a href="http://english.ryukyushimpo.jp/2011/10/06/3083/" rel="bookmark" title="2011年10月6日">Awamori Meister Association concludes a sister-organization agreement with its counterpart in Taiwan</a>,
 <a href="http://english.ryukyushimpo.jp/2019/06/21/30573/" rel="bookmark" title="2019年6月21日">Okinawa to host the world’s largest travel conference Tourism Expo Japan 2020, in October of 2020, will also host ministerial summit</a>,
 <a href="http://english.ryukyushimpo.jp/2020/03/13/31753/" rel="bookmark" title="2020年3月13日">Okinawa to raise Employment Adjustment Subsidy as an emergency measure to aid businesses affected by the coronavirus</a>,
 <a href="http://english.ryukyushimpo.jp/2020/04/03/31827/" rel="bookmark" title="2020年4月3日">Okinawan economic organizations come together to call for aid for business owners from Governor Tamaki amid coronavirus pandemic</a>,
 <a href="http://english.ryukyushimpo.jp/2015/01/06/16544/" rel="bookmark" title="2015年1月6日">Yokota wins Miss <em>Onna Nabi</em> crown</a>,
 <a href="http://english.ryukyushimpo.jp/kokusai-street-naha-livecamera/">
 <img alt="webcam-image" border="0" height="200" hspace="5" src="http://english.ryukyushimpo.jp/wp-content/uploads/2019/06/webcam3.jpg" vspace="5" width="320"/>
 <!-- <IFRAME border=0 name="" src="http://222.147.115.202:50000/ImageViewer?Resolution=320x240&Quality=Standard&Mode=Motion" width=320 scrolling=no height=240></IFRAME>
 <IFRAME name=body src="http://222.147.115.202:50000/ViewerFrame?page=Single&RPeriod=60&Resolution=320x240&Quality=Standard&Size=STD"></IFRAME>
 -->
 Webcam(Kokusai Street)
 </a>,
 <a href="http://english.ryukyushimpo.jp/2022/06/10/34707/">Moving the Ryukyu Shimpo English News site !</a>,
 <a href="http://english.ryukyushimpo.jp/2022/05/31/34704/">Independent investigation on toxic PFAS levels in six municipalities underway</a>,
 <a href="http://english.ryukyushimpo.jp/2022/05/31/34701/">Naha Airport to partially reopen international travel routes in June, lifting a two-year tourism restriction</a>,
 <a href="http://english.ryukyushimpo.jp/2022/05/31/34698/">1,000 people rally in Tokyo for protection of the constitution and no base in Henoko</a>,
 <a href="http://english.ryukyushimpo.jp/2022/05/27/34695/">Walking tour of Koza resumes after three-year hiatus, including the taco stand featured in the movie “Miracle City Koza”</a>,
 <a class="widget_sp_image-image-link" href="http://english.kyodonews.jp/" target="_blank"><img class="attachment-full" height="80" src="http://english.ryukyushimpo.jp/wp-content/uploads/2015/08/logo_kyodo2.gif" style="max-width: 100%;" width="280"/></a>,
 <a class="widget_sp_image-image-link" href="http://www.fukushimaminponews.com/" target="_blank"><img class="attachment-full" height="80" src="http://english.ryukyushimpo.jp/wp-content/uploads/2015/08/minpo2-31.jpg" style="max-width: 100%;" width="280"/></a>,
 <a class="widget_sp_image-image-link" href="http://www.kyoto-np.co.jp/kp/english/" target="_blank"><img class="attachment-full" height="80" src="http://english.ryukyushimpo.jp/wp-content/uploads/2015/08/kyoto_news.jpg" style="max-width: 100%;" width="280"/></a>,
 <a href="http://english.ryukyushimpo.jp/category/animal-and-plant/">animal &amp; plant</a>,
 <a href="http://english.ryukyushimpo.jp/category/art/">art</a>,
 <a href="http://english.ryukyushimpo.jp/category/art-entertainment/">Art &amp; entertainment</a>,
 <a href="http://english.ryukyushimpo.jp/category/arts-culture/">Arts &amp; Culture</a>,
 <a href="http://english.ryukyushimpo.jp/category/awamori-2/">Awamori</a>,
 <a href="http://english.ryukyushimpo.jp/category/battle-of-okinawa/">Battle of Okinawa</a>,
 <a href="http://english.ryukyushimpo.jp/category/business/">Business</a>,
 <a href="http://english.ryukyushimpo.jp/category/column/">Column</a>,
 <a href="http://english.ryukyushimpo.jp/category/community/">Community</a>,
 <a href="http://english.ryukyushimpo.jp/category/culture/">Culture</a>,
 <a href="http://english.ryukyushimpo.jp/category/culture-and-arts/">Culture and Arts</a>,
 <a href="http://english.ryukyushimpo.jp/category/economics/">Economics</a>,
 <a href="http://english.ryukyushimpo.jp/category/economy/">Economy</a>,
 <a href="http://english.ryukyushimpo.jp/category/editorial/">Editorial</a>,
 <a href="http://english.ryukyushimpo.jp/category/education/">Education</a>,
 <a href="http://english.ryukyushimpo.jp/category/entertainment/">Entertainment</a>,
 <a href="http://english.ryukyushimpo.jp/category/entertainment-and-culture/">Entertainment and culture</a>,
 <a href="http://english.ryukyushimpo.jp/category/environment/">environment</a>,
 <a href="http://english.ryukyushimpo.jp/category/extra-edition/">Extra edition:</a>,
 <a href="http://english.ryukyushimpo.jp/category/futenma/">Futenma</a>,
 <a href="http://english.ryukyushimpo.jp/category/futenma-air-station-relocation-issue/">Futenma Air Station relocation issue</a>,
 <a href="http://english.ryukyushimpo.jp/category/henoko-new-us-base-construction/">Henoko new US base construction</a>,
 <a href="http://english.ryukyushimpo.jp/category/information/">Information</a>,
 <a href="http://english.ryukyushimpo.jp/category/international/">International</a>,
 <a href="http://english.ryukyushimpo.jp/category/leisure/">Leisure</a>,
 <a href="http://english.ryukyushimpo.jp/category/life/">Life</a>,
 <a href="http://english.ryukyushimpo.jp/category/lifestyle/">Lifestyle</a>,
 <a href="http://english.ryukyushimpo.jp/category/living/">Living</a>,
 <a href="http://english.ryukyushimpo.jp/category/local/">Local</a>,
 <a href="http://english.ryukyushimpo.jp/category/media-suppression-issue/">Media Suppression Issue</a>,
 <a href="http://english.ryukyushimpo.jp/category/news/">News</a>,
 <a href="http://english.ryukyushimpo.jp/category/news-brief-compiled-from-ryukyu-shimpo-reports/">News brief compiled from Ryukyu Shimpo reports</a>,
 <a href="http://english.ryukyushimpo.jp/category/okinawa-memorial-day/">Okinawa Memorial Day</a>,
 <a href="http://english.ryukyushimpo.jp/category/okinawas-unexploded/">Okinawa's unexploded ordnance</a>,
 <a href="http://english.ryukyushimpo.jp/category/osprey/">Osprey</a>,
 <a href="http://english.ryukyushimpo.jp/category/other/">Other</a>,
 <a href="http://english.ryukyushimpo.jp/category/peace-education-2/">Peace Education</a>,
 <a href="http://english.ryukyushimpo.jp/category/people/">People</a>,
 <a href="http://english.ryukyushimpo.jp/category/performing-arts-and-culture/">Performing arts and culture</a>,
 <a href="http://english.ryukyushimpo.jp/category/politics/">Politics</a>,
 <a href="http://english.ryukyushimpo.jp/category/region/">Region</a>,
 <a href="http://english.ryukyushimpo.jp/category/regional/">Regional</a>,
 <a href="http://english.ryukyushimpo.jp/category/slideshow/">slideshow</a>,
 <a href="http://english.ryukyushimpo.jp/category/social/">Social</a>,
 <a href="http://english.ryukyushimpo.jp/category/society/">Society</a>,
 <a href="http://english.ryukyushimpo.jp/category/special-editorial/">Special Editorial</a>,
 <a href="http://english.ryukyushimpo.jp/category/special-page/">Special page</a>,
 <a href="http://english.ryukyushimpo.jp/category/sports/">Sports</a>,
 <a href="http://english.ryukyushimpo.jp/category/style/">Style</a>,
 <a href="http://english.ryukyushimpo.jp/category/typhoon/">Typhoon</a>,
 <a href="http://english.ryukyushimpo.jp/category/u-s-military-crimes-and-incidents/">U.S. military crimes and incidents</a>,
 <a href="http://english.ryukyushimpo.jp/category/uchinaguchi/">Uchinaguchi</a>,
 <a href="http://english.ryukyushimpo.jp/category/uchinanchu-in-the-world/">Uchinanchu in the world</a>,
 <a href="http://english.ryukyushimpo.jp/category/video/">video</a>,
 <a href="http://english.ryukyushimpo.jp/category/wuf5th/">wuf5th</a>,
 <a href="http://english.ryukyushimpo.jp/category/%e6%9c%aa%e5%88%86%e9%a1%9e/">未分類</a>,
 <a href="http://english.ryukyushimpo.jp/about-us-2/">About Us</a>,
 <a href="http://english.ryukyushimpo.jp/awards/">Awards</a>,
 <a href="http://english.ryukyushimpo.jp/company-policy-and-editing-principles/">Company Policy and Editing Principles</a>,
 <a href="http://english.ryukyushimpo.jp/contact-us2/">Contact Us</a>,
 <a href="http://english.ryukyushimpo.jp/from-ryukyu-shimpo-inc/">From Ryukyu Shimpo, Inc.</a>,
 <a href="http://english.ryukyushimpo.jp/governor-onaga-un-speech-special-feature/">Governor Onaga UN Speech Special Feature</a>,
 <a href="http://english.ryukyushimpo.jp/news-and-editorial-staff/">News and Editorial Staff</a>,
 <a href="http://english.ryukyushimpo.jp/privacy-policy/">Privacy Policy</a>,
 <a href="http://english.ryukyushimpo.jp/ryukyu-shimpo-company-history/">Ryukyu Shimpo Company History</a>,
 <a href="http://english.ryukyushimpo.jp/site-policy/">Site Policy</a>,
 <a href="http://english.ryukyushimpo.jp/%e8%87%aa%e5%8b%95%e4%b8%8b%e6%9b%b8%e3%81%8d/">自動下書き</a>,
 <a href="https://www.facebook.com/english.ryukyushimpo.jp" title="english.ryukyushimpo.jp’s Facebook page">Facebook Page</a>,
 <a href="https://plus.google.com/s/The%20Ryukyu%20Shimpo#110885466983766797064/posts" title="english.ryukyushimpo.jp’s Google+ page">Google+ page</a>,
 <a href="http://japanfocus.org/" title="The Asia-Pacific Journal:Japan Focus">Japan Focus</a>,
 <a href="http://english.ryukyushimpo.jp/kokusai-street-naha-livecamera/" title="Kokusai Street, Naha-live camera">Live Camera</a>,
 <a href="http://www.pref.okinawa.jp/english/index.html" title="Okinawa Prefecture English Home">Okinawa Prefecture</a>,
 <a href="http://ryukyushimpo.jp/">Ryukyu shimpo　(Japanese)</a>,
 <a href="http://www.youtube.com/user/ryukyushimpo">Youtube my channel</a>,
 <a href="http://english.ryukyushimpo.jp/feed/" title="english.ryukyushimpo.jp – RSS Feed">RSS Feed</a>,
 <a href="http://english.ryukyushimpo.jp/2022/06/">2022年June</a>,
 <a href="http://english.ryukyushimpo.jp/2022/05/">2022年May</a>,
 <a href="http://english.ryukyushimpo.jp/2022/04/">2022年April</a>,
 <a href="http://english.ryukyushimpo.jp/2022/03/">2022年March</a>,
 <a href="http://english.ryukyushimpo.jp/2022/02/">2022年February</a>,
 <a href="http://english.ryukyushimpo.jp/2022/01/">2022年January</a>,
 <a href="http://english.ryukyushimpo.jp/2021/12/">2021年December</a>,
 <a href="http://english.ryukyushimpo.jp/2021/11/">2021年November</a>,
 <a href="http://english.ryukyushimpo.jp/2021/10/">2021年October</a>,
 <a href="http://english.ryukyushimpo.jp/2021/09/">2021年September</a>,
 <a href="http://english.ryukyushimpo.jp/2021/08/">2021年August</a>,
 <a href="http://english.ryukyushimpo.jp/2021/07/">2021年July</a>,
 <a href="http://english.ryukyushimpo.jp/2021/06/">2021年June</a>,
 <a href="http://english.ryukyushimpo.jp/2021/05/">2021年May</a>,
 <a href="http://english.ryukyushimpo.jp/2021/04/">2021年April</a>,
 <a href="http://english.ryukyushimpo.jp/2021/03/">2021年March</a>,
 <a href="http://english.ryukyushimpo.jp/2021/02/">2021年February</a>,
 <a href="http://english.ryukyushimpo.jp/2021/01/">2021年January</a>,
 <a href="http://english.ryukyushimpo.jp/2020/12/">2020年December</a>,
 <a href="http://english.ryukyushimpo.jp/2020/11/">2020年November</a>,
 <a href="http://english.ryukyushimpo.jp/2020/10/">2020年October</a>,
 <a href="http://english.ryukyushimpo.jp/2020/09/">2020年September</a>,
 <a href="http://english.ryukyushimpo.jp/2020/08/">2020年August</a>,
 <a href="http://english.ryukyushimpo.jp/2020/07/">2020年July</a>,
 <a href="http://english.ryukyushimpo.jp/2020/06/">2020年June</a>,
 <a href="http://english.ryukyushimpo.jp/2020/05/">2020年May</a>,
 <a href="http://english.ryukyushimpo.jp/2020/04/">2020年April</a>,
 <a href="http://english.ryukyushimpo.jp/2020/03/">2020年March</a>,
 <a href="http://english.ryukyushimpo.jp/2020/02/">2020年February</a>,
 <a href="http://english.ryukyushimpo.jp/2020/01/">2020年January</a>,
 <a href="http://english.ryukyushimpo.jp/2019/12/">2019年December</a>,
 <a href="http://english.ryukyushimpo.jp/2019/11/">2019年November</a>,
 <a href="http://english.ryukyushimpo.jp/2019/10/">2019年October</a>,
 <a href="http://english.ryukyushimpo.jp/2019/09/">2019年September</a>,
 <a href="http://english.ryukyushimpo.jp/2019/08/">2019年August</a>,
 <a href="http://english.ryukyushimpo.jp/2019/07/">2019年July</a>,
 <a href="http://english.ryukyushimpo.jp/2019/06/">2019年June</a>,
 <a href="http://english.ryukyushimpo.jp/2019/05/">2019年May</a>,
 <a href="http://english.ryukyushimpo.jp/2019/04/">2019年April</a>,
 <a href="http://english.ryukyushimpo.jp/2019/03/">2019年March</a>,
 <a href="http://english.ryukyushimpo.jp/2019/02/">2019年February</a>,
 <a href="http://english.ryukyushimpo.jp/2019/01/">2019年January</a>,
 <a href="http://english.ryukyushimpo.jp/2018/12/">2018年December</a>,
 <a href="http://english.ryukyushimpo.jp/2018/11/">2018年November</a>,
 <a href="http://english.ryukyushimpo.jp/2018/10/">2018年October</a>,
 <a href="http://english.ryukyushimpo.jp/2018/09/">2018年September</a>,
 <a href="http://english.ryukyushimpo.jp/2018/08/">2018年August</a>,
 <a href="http://english.ryukyushimpo.jp/2018/07/">2018年July</a>,
 <a href="http://english.ryukyushimpo.jp/2018/06/">2018年June</a>,
 <a href="http://english.ryukyushimpo.jp/2018/05/">2018年May</a>,
 <a href="http://english.ryukyushimpo.jp/2018/04/">2018年April</a>,
 <a href="http://english.ryukyushimpo.jp/2018/03/">2018年March</a>,
 <a href="http://english.ryukyushimpo.jp/2018/02/">2018年February</a>,
 <a href="http://english.ryukyushimpo.jp/2018/01/">2018年January</a>,
 <a href="http://english.ryukyushimpo.jp/2017/12/">2017年December</a>,
 <a href="http://english.ryukyushimpo.jp/2017/11/">2017年November</a>,
 <a href="http://english.ryukyushimpo.jp/2017/10/">2017年October</a>,
 <a href="http://english.ryukyushimpo.jp/2017/09/">2017年September</a>,
 <a href="http://english.ryukyushimpo.jp/2017/08/">2017年August</a>,
 <a href="http://english.ryukyushimpo.jp/2017/07/">2017年July</a>,
 <a href="http://english.ryukyushimpo.jp/2017/06/">2017年June</a>,
 <a href="http://english.ryukyushimpo.jp/2017/05/">2017年May</a>,
 <a href="http://english.ryukyushimpo.jp/2017/04/">2017年April</a>,
 <a href="http://english.ryukyushimpo.jp/2017/03/">2017年March</a>,
 <a href="http://english.ryukyushimpo.jp/2017/02/">2017年February</a>,
 <a href="http://english.ryukyushimpo.jp/2017/01/">2017年January</a>,
 <a href="http://english.ryukyushimpo.jp/2016/12/">2016年December</a>,
 <a href="http://english.ryukyushimpo.jp/2016/11/">2016年November</a>,
 <a href="http://english.ryukyushimpo.jp/2016/10/">2016年October</a>,
 <a href="http://english.ryukyushimpo.jp/2016/09/">2016年September</a>,
 <a href="http://english.ryukyushimpo.jp/2016/08/">2016年August</a>,
 <a href="http://english.ryukyushimpo.jp/2016/07/">2016年July</a>,
 <a href="http://english.ryukyushimpo.jp/2016/06/">2016年June</a>,
 <a href="http://english.ryukyushimpo.jp/2016/05/">2016年May</a>,
 <a href="http://english.ryukyushimpo.jp/2016/04/">2016年April</a>,
 <a href="http://english.ryukyushimpo.jp/2016/03/">2016年March</a>,
 <a href="http://english.ryukyushimpo.jp/2016/02/">2016年February</a>,
 <a href="http://english.ryukyushimpo.jp/2016/01/">2016年January</a>,
 <a href="http://english.ryukyushimpo.jp/2015/12/">2015年December</a>,
 <a href="http://english.ryukyushimpo.jp/2015/11/">2015年November</a>,
 <a href="http://english.ryukyushimpo.jp/2015/10/">2015年October</a>,
 <a href="http://english.ryukyushimpo.jp/2015/09/">2015年September</a>,
 <a href="http://english.ryukyushimpo.jp/2015/08/">2015年August</a>,
 <a href="http://english.ryukyushimpo.jp/2015/07/">2015年July</a>,
 <a href="http://english.ryukyushimpo.jp/2015/06/">2015年June</a>,
 <a href="http://english.ryukyushimpo.jp/2015/05/">2015年May</a>,
 <a href="http://english.ryukyushimpo.jp/2015/04/">2015年April</a>,
 <a href="http://english.ryukyushimpo.jp/2015/03/">2015年March</a>,
 <a href="http://english.ryukyushimpo.jp/2015/02/">2015年February</a>,
 <a href="http://english.ryukyushimpo.jp/2015/01/">2015年January</a>,
 <a href="http://english.ryukyushimpo.jp/2014/12/">2014年December</a>,
 <a href="http://english.ryukyushimpo.jp/2014/11/">2014年November</a>,
 <a href="http://english.ryukyushimpo.jp/2014/10/">2014年October</a>,
 <a href="http://english.ryukyushimpo.jp/2014/09/">2014年September</a>,
 <a href="http://english.ryukyushimpo.jp/2014/08/">2014年August</a>,
 <a href="http://english.ryukyushimpo.jp/2014/07/">2014年July</a>,
 <a href="http://english.ryukyushimpo.jp/2014/06/">2014年June</a>,
 <a href="http://english.ryukyushimpo.jp/2014/05/">2014年May</a>,
 <a href="http://english.ryukyushimpo.jp/2014/04/">2014年April</a>,
 <a href="http://english.ryukyushimpo.jp/2014/03/">2014年March</a>,
 <a href="http://english.ryukyushimpo.jp/2014/02/">2014年February</a>,
 <a href="http://english.ryukyushimpo.jp/2014/01/">2014年January</a>,
 <a href="http://english.ryukyushimpo.jp/2013/12/">2013年December</a>,
 <a href="http://english.ryukyushimpo.jp/2013/11/">2013年November</a>,
 <a href="http://english.ryukyushimpo.jp/2013/10/">2013年October</a>,
 <a href="http://english.ryukyushimpo.jp/2013/09/">2013年September</a>,
 <a href="http://english.ryukyushimpo.jp/2013/08/">2013年August</a>,
 <a href="http://english.ryukyushimpo.jp/2013/07/">2013年July</a>,
 <a href="http://english.ryukyushimpo.jp/2013/06/">2013年June</a>,
 <a href="http://english.ryukyushimpo.jp/2013/05/">2013年May</a>,
 <a href="http://english.ryukyushimpo.jp/2013/04/">2013年April</a>,
 <a href="http://english.ryukyushimpo.jp/2013/03/">2013年March</a>,
 <a href="http://english.ryukyushimpo.jp/2013/02/">2013年February</a>,
 <a href="http://english.ryukyushimpo.jp/2013/01/">2013年January</a>,
 <a href="http://english.ryukyushimpo.jp/2012/12/">2012年December</a>,
 <a href="http://english.ryukyushimpo.jp/2012/11/">2012年November</a>,
 <a href="http://english.ryukyushimpo.jp/2012/10/">2012年October</a>,
 <a href="http://english.ryukyushimpo.jp/2012/09/">2012年September</a>,
 <a href="http://english.ryukyushimpo.jp/2012/08/">2012年August</a>,
 <a href="http://english.ryukyushimpo.jp/2012/07/">2012年July</a>,
 <a href="http://english.ryukyushimpo.jp/2012/06/">2012年June</a>,
 <a href="http://english.ryukyushimpo.jp/2012/05/">2012年May</a>,
 <a href="http://english.ryukyushimpo.jp/2012/04/">2012年April</a>,
 <a href="http://english.ryukyushimpo.jp/2012/03/">2012年March</a>,
 <a href="http://english.ryukyushimpo.jp/2012/02/">2012年February</a>,
 <a href="http://english.ryukyushimpo.jp/2012/01/">2012年January</a>,
 <a href="http://english.ryukyushimpo.jp/2011/12/">2011年December</a>,
 <a href="http://english.ryukyushimpo.jp/2011/11/">2011年November</a>,
 <a href="http://english.ryukyushimpo.jp/2011/10/">2011年October</a>,
 <a href="http://english.ryukyushimpo.jp/2011/09/">2011年September</a>,
 <a href="http://english.ryukyushimpo.jp/2011/08/">2011年August</a>,